CC=gcc
CFLAGS=-I.
all : parallel.elf
parallel.elf : utils.o find_min_max.o utils.h find_min_max.h
	$(CC) -o parallel.elf utils.o find_min_max.o parallel_min_max.c $(CFLAGS)

utils.o : utils.h
	$(CC) -o utils.o -c utils.c $(CFLAGS)

find_min_max.o : utils.h find_min_max.h
	$(CC) -o find_min_max.o -c find_min_max.c $(CFLAGS)
clean :
	rm utils.o find_min_max.o parallel.elf